<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ToastCloud\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ToastCloud\ApiException;
use ToastCloud\Configuration;
use ToastCloud\HeaderSelector;
use ToastCloud\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation appKeySenderEachMailPost
     *
     * 개별 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\MailBody $body body (required)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function appKeySenderEachMailPost($appKey, $body)
    {
        $this->appKeySenderEachMailPostWithHttpInfo($appKey, $body);
    }

    /**
     * Operation appKeySenderEachMailPostWithHttpInfo
     *
     * 개별 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\MailBody $body (required)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function appKeySenderEachMailPostWithHttpInfo($appKey, $body)
    {
        $returnType = '';
        $request = $this->appKeySenderEachMailPostRequest($appKey, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation appKeySenderEachMailPostAsync
     *
     * 개별 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\MailBody $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appKeySenderEachMailPostAsync($appKey, $body)
    {
        return $this->appKeySenderEachMailPostAsyncWithHttpInfo($appKey, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation appKeySenderEachMailPostAsyncWithHttpInfo
     *
     * 개별 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\MailBody $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appKeySenderEachMailPostAsyncWithHttpInfo($appKey, $body)
    {
        $returnType = '';
        $request = $this->appKeySenderEachMailPostRequest($appKey, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'appKeySenderEachMailPost'
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\MailBody $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function appKeySenderEachMailPostRequest($appKey, $body)
    {
        // verify the required parameter 'appKey' is set
        if ($appKey === null || (is_array($appKey) && count($appKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $appKey when calling appKeySenderEachMailPost'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling appKeySenderEachMailPost'
            );
        }

        $resourcePath = '/{appKey}/sender/eachMail';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($appKey !== null) {
            $resourcePath = str_replace(
                '{' . 'appKey' . '}',
                ObjectSerializer::toPathValue($appKey),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation appKeySenderMailsGet
     *
     * 메일 발송 리스트 조회
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  string $requestId 요청 ID (조건적 필수 - 1) (optional)
     * @param  string $startSendDate 발송 시점 조회 시작값 (조건적 필수 - 2) (optional)
     * @param  string $endSendDate 발송 시점 조회 종료값 (조건적 필수 - 2) (optional)
     * @param  string $mailStatusCode 발송상태코드 (발송준비, 발송중, 발송완료, 발송실패 순) (optional)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function appKeySenderMailsGet($appKey, $requestId = null, $startSendDate = null, $endSendDate = null, $mailStatusCode = null)
    {
        $this->appKeySenderMailsGetWithHttpInfo($appKey, $requestId, $startSendDate, $endSendDate, $mailStatusCode);
    }

    /**
     * Operation appKeySenderMailsGetWithHttpInfo
     *
     * 메일 발송 리스트 조회
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  string $requestId 요청 ID (조건적 필수 - 1) (optional)
     * @param  string $startSendDate 발송 시점 조회 시작값 (조건적 필수 - 2) (optional)
     * @param  string $endSendDate 발송 시점 조회 종료값 (조건적 필수 - 2) (optional)
     * @param  string $mailStatusCode 발송상태코드 (발송준비, 발송중, 발송완료, 발송실패 순) (optional)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function appKeySenderMailsGetWithHttpInfo($appKey, $requestId = null, $startSendDate = null, $endSendDate = null, $mailStatusCode = null)
    {
        $returnType = '';
        $request = $this->appKeySenderMailsGetRequest($appKey, $requestId, $startSendDate, $endSendDate, $mailStatusCode);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation appKeySenderMailsGetAsync
     *
     * 메일 발송 리스트 조회
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  string $requestId 요청 ID (조건적 필수 - 1) (optional)
     * @param  string $startSendDate 발송 시점 조회 시작값 (조건적 필수 - 2) (optional)
     * @param  string $endSendDate 발송 시점 조회 종료값 (조건적 필수 - 2) (optional)
     * @param  string $mailStatusCode 발송상태코드 (발송준비, 발송중, 발송완료, 발송실패 순) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appKeySenderMailsGetAsync($appKey, $requestId = null, $startSendDate = null, $endSendDate = null, $mailStatusCode = null)
    {
        return $this->appKeySenderMailsGetAsyncWithHttpInfo($appKey, $requestId, $startSendDate, $endSendDate, $mailStatusCode)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation appKeySenderMailsGetAsyncWithHttpInfo
     *
     * 메일 발송 리스트 조회
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  string $requestId 요청 ID (조건적 필수 - 1) (optional)
     * @param  string $startSendDate 발송 시점 조회 시작값 (조건적 필수 - 2) (optional)
     * @param  string $endSendDate 발송 시점 조회 종료값 (조건적 필수 - 2) (optional)
     * @param  string $mailStatusCode 발송상태코드 (발송준비, 발송중, 발송완료, 발송실패 순) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appKeySenderMailsGetAsyncWithHttpInfo($appKey, $requestId = null, $startSendDate = null, $endSendDate = null, $mailStatusCode = null)
    {
        $returnType = '';
        $request = $this->appKeySenderMailsGetRequest($appKey, $requestId, $startSendDate, $endSendDate, $mailStatusCode);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'appKeySenderMailsGet'
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  string $requestId 요청 ID (조건적 필수 - 1) (optional)
     * @param  string $startSendDate 발송 시점 조회 시작값 (조건적 필수 - 2) (optional)
     * @param  string $endSendDate 발송 시점 조회 종료값 (조건적 필수 - 2) (optional)
     * @param  string $mailStatusCode 발송상태코드 (발송준비, 발송중, 발송완료, 발송실패 순) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function appKeySenderMailsGetRequest($appKey, $requestId = null, $startSendDate = null, $endSendDate = null, $mailStatusCode = null)
    {
        // verify the required parameter 'appKey' is set
        if ($appKey === null || (is_array($appKey) && count($appKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $appKey when calling appKeySenderMailsGet'
            );
        }

        $resourcePath = '/{appKey}/sender/mails';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($requestId !== null) {
            $queryParams['requestId'] = ObjectSerializer::toQueryValue($requestId);
        }
        // query params
        if ($startSendDate !== null) {
            $queryParams['startSendDate'] = ObjectSerializer::toQueryValue($startSendDate);
        }
        // query params
        if ($endSendDate !== null) {
            $queryParams['endSendDate'] = ObjectSerializer::toQueryValue($endSendDate);
        }
        // query params
        if ($mailStatusCode !== null) {
            $queryParams['mailStatusCode'] = ObjectSerializer::toQueryValue($mailStatusCode);
        }

        // path params
        if ($appKey !== null) {
            $resourcePath = str_replace(
                '{' . 'appKey' . '}',
                ObjectSerializer::toPathValue($appKey),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['appication/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendMail
     *
     * 일반 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\Receiver $body body (required)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendMail($appKey, $body)
    {
        $this->sendMailWithHttpInfo($appKey, $body);
    }

    /**
     * Operation sendMailWithHttpInfo
     *
     * 일반 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\Receiver $body (required)
     *
     * @throws \ToastCloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendMailWithHttpInfo($appKey, $body)
    {
        $returnType = '';
        $request = $this->sendMailRequest($appKey, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation sendMailAsync
     *
     * 일반 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\Receiver $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMailAsync($appKey, $body)
    {
        return $this->sendMailAsyncWithHttpInfo($appKey, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendMailAsyncWithHttpInfo
     *
     * 일반 메일 발송
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\Receiver $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMailAsyncWithHttpInfo($appKey, $body)
    {
        $returnType = '';
        $request = $this->sendMailRequest($appKey, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendMail'
     *
     * @param  string $appKey Project별 고유의 앱키 (required)
     * @param  \ToastCloud\Model\Receiver $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendMailRequest($appKey, $body)
    {
        // verify the required parameter 'appKey' is set
        if ($appKey === null || (is_array($appKey) && count($appKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $appKey when calling sendMail'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling sendMail'
            );
        }

        $resourcePath = '/{appKey}/sender/mail';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($appKey !== null) {
            $resourcePath = str_replace(
                '{' . 'appKey' . '}',
                ObjectSerializer::toPathValue($appKey),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
