<?php
/**
 * ResponseBodyItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ToastCloud\Model;

use \ArrayAccess;
use \ToastCloud\ObjectSerializer;

/**
 * ResponseBodyItem Class Doc Comment
 *
 * @category Class
 * @description responseBody에서 각 수신자의 발송 결과 항목
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseBodyItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'responseBodyItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'receiveMailAddr' => '\ToastCloud\Model\ReceiverPropertiesReceiveMailAddr',
        'recieveName' => '\ToastCloud\Model\ReceiverPropertiesReceiveName',
        'receiveType' => '\ToastCloud\Model\ReceiverPropertiesReceiveType',
        'resultCode' => 'int',
        'resultMessage' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'receiveMailAddr' => null,
        'recieveName' => null,
        'receiveType' => null,
        'resultCode' => null,
        'resultMessage' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'receiveMailAddr' => 'receiveMailAddr',
        'recieveName' => 'recieveName',
        'receiveType' => 'receiveType',
        'resultCode' => 'resultCode',
        'resultMessage' => 'resultMessage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'receiveMailAddr' => 'setReceiveMailAddr',
        'recieveName' => 'setRecieveName',
        'receiveType' => 'setReceiveType',
        'resultCode' => 'setResultCode',
        'resultMessage' => 'setResultMessage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'receiveMailAddr' => 'getReceiveMailAddr',
        'recieveName' => 'getRecieveName',
        'receiveType' => 'getReceiveType',
        'resultCode' => 'getResultCode',
        'resultMessage' => 'getResultMessage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['receiveMailAddr'] = isset($data['receiveMailAddr']) ? $data['receiveMailAddr'] : null;
        $this->container['recieveName'] = isset($data['recieveName']) ? $data['recieveName'] : null;
        $this->container['receiveType'] = isset($data['receiveType']) ? $data['receiveType'] : null;
        $this->container['resultCode'] = isset($data['resultCode']) ? $data['resultCode'] : null;
        $this->container['resultMessage'] = isset($data['resultMessage']) ? $data['resultMessage'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets receiveMailAddr
     *
     * @return \ToastCloud\Model\ReceiverPropertiesReceiveMailAddr
     */
    public function getReceiveMailAddr()
    {
        return $this->container['receiveMailAddr'];
    }

    /**
     * Sets receiveMailAddr
     *
     * @param \ToastCloud\Model\ReceiverPropertiesReceiveMailAddr $receiveMailAddr receiveMailAddr
     *
     * @return $this
     */
    public function setReceiveMailAddr($receiveMailAddr)
    {
        $this->container['receiveMailAddr'] = $receiveMailAddr;

        return $this;
    }

    /**
     * Gets recieveName
     *
     * @return \ToastCloud\Model\ReceiverPropertiesReceiveName
     */
    public function getRecieveName()
    {
        return $this->container['recieveName'];
    }

    /**
     * Sets recieveName
     *
     * @param \ToastCloud\Model\ReceiverPropertiesReceiveName $recieveName recieveName
     *
     * @return $this
     */
    public function setRecieveName($recieveName)
    {
        $this->container['recieveName'] = $recieveName;

        return $this;
    }

    /**
     * Gets receiveType
     *
     * @return \ToastCloud\Model\ReceiverPropertiesReceiveType
     */
    public function getReceiveType()
    {
        return $this->container['receiveType'];
    }

    /**
     * Sets receiveType
     *
     * @param \ToastCloud\Model\ReceiverPropertiesReceiveType $receiveType receiveType
     *
     * @return $this
     */
    public function setReceiveType($receiveType)
    {
        $this->container['receiveType'] = $receiveType;

        return $this;
    }

    /**
     * Gets resultCode
     *
     * @return int
     */
    public function getResultCode()
    {
        return $this->container['resultCode'];
    }

    /**
     * Sets resultCode
     *
     * @param int $resultCode 수신자 발송 요청 결과 코드
     *
     * @return $this
     */
    public function setResultCode($resultCode)
    {
        $this->container['resultCode'] = $resultCode;

        return $this;
    }

    /**
     * Gets resultMessage
     *
     * @return string
     */
    public function getResultMessage()
    {
        return $this->container['resultMessage'];
    }

    /**
     * Sets resultMessage
     *
     * @param string $resultMessage 수신자 발송 요청 결과 메세지
     *
     * @return $this
     */
    public function setResultMessage($resultMessage)
    {
        $this->container['resultMessage'] = $resultMessage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


