<?php
/**
 * MailBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ToastCloud;

/**
 * MailBodyTest Class Doc Comment
 *
 * @category    Class
 * @description MailBody
 * @package     ToastCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MailBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MailBody"
     */
    public function testMailBody()
    {
    }

    /**
     * Test attribute "senderAddress"
     */
    public function testPropertySenderAddress()
    {
    }

    /**
     * Test attribute "senderName"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "requestDate"
     */
    public function testPropertyRequestDate()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "attachFieldList"
     */
    public function testPropertyAttachFieldList()
    {
    }

    /**
     * Test attribute "recieverList"
     */
    public function testPropertyRecieverList()
    {
    }
}
