<?php
/**
 * ReceiverTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ToastCloud;

/**
 * ReceiverTest Class Doc Comment
 *
 * @category    Class
 * @description Receiver
 * @package     ToastCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReceiverTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Receiver"
     */
    public function testReceiver()
    {
    }

    /**
     * Test attribute "receiveMailAddr"
     */
    public function testPropertyReceiveMailAddr()
    {
    }

    /**
     * Test attribute "receiveName"
     */
    public function testPropertyReceiveName()
    {
    }

    /**
     * Test attribute "receiveType"
     */
    public function testPropertyReceiveType()
    {
    }
}
