<?php
/**
 * ResponseBodyItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ToastCloud;

/**
 * ResponseBodyItemTest Class Doc Comment
 *
 * @category    Class
 * @description responseBody에서 각 수신자의 발송 결과 항목
 * @package     ToastCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseBodyItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseBodyItem"
     */
    public function testResponseBodyItem()
    {
    }

    /**
     * Test attribute "receiveMailAddr"
     */
    public function testPropertyReceiveMailAddr()
    {
    }

    /**
     * Test attribute "recieveName"
     */
    public function testPropertyRecieveName()
    {
    }

    /**
     * Test attribute "receiveType"
     */
    public function testPropertyReceiveType()
    {
    }

    /**
     * Test attribute "resultCode"
     */
    public function testPropertyResultCode()
    {
    }

    /**
     * Test attribute "resultMessage"
     */
    public function testPropertyResultMessage()
    {
    }
}
