<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ToastCloud;

use \ToastCloud\Configuration;
use \ToastCloud\ApiException;
use \ToastCloud\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appKeySenderEachMailPost
     *
     * 개별 메일 발송.
     *
     */
    public function testAppKeySenderEachMailPost()
    {
    }

    /**
     * Test case for appKeySenderMailsGet
     *
     * 메일 발송 리스트 조회.
     *
     */
    public function testAppKeySenderMailsGet()
    {
    }

    /**
     * Test case for sendMail
     *
     * 일반 메일 발송.
     *
     */
    public function testSendMail()
    {
    }
}
